FROM python:3.11-slim

WORKDIR /main

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

#COMMAND TO START THE FASTAPI APP 
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]

