[project]
name = "rag-eval-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sumran Harchirkar", email = "sumranharchirkar58@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "deepeval>=4.2.1",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.6.1",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-text-splitters>=1.1.2",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
rag-eval-project = "rag_eval_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
